name = "RecurrenceRelationships"
uuid = "807425ed-42ea-44d6-a357-6771516d7b2c"
authors = ["Sheehan Olver <solver@mac.com>"]
version = "0.2.0"

[weakdeps]
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extensions]
RecurrenceRelationshipsFillArraysExt = "FillArrays"
RecurrenceRelationshipsLazyArraysExt = "LazyArrays"
RecurrenceRelationshipsLinearAlgebraExt = "LinearAlgebra"

[compat]
DynamicPolynomials = "0.6.1"
FillArrays = "1"
LazyArrays = "1, 2"
SpecialFunctions = "1, 2"
julia = "1.10"

[extras]
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DynamicPolynomials", "FillArrays", "LazyArrays", "LinearAlgebra", "SpecialFunctions", "Test"]
